name: Gh-Pages

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch: # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Flutter
      uses: subosito/flutter-action@v2

    - name: Create firebase_options.dart from secret
      env:
        FIREBASE_OPTIONS_FILE: ${{ secrets.FIREBASE_OPTIONS_FILE }}
      run: |
        echo "$FIREBASE_OPTIONS_FILE" > lib/firebase_options.dart

    - name: Build Flutter Web (PR/Manual)
      if: github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch'
      run: |
        flutter pub get
        flutter build web --release
        
    - name: Deploy to GitHub Pages (Main branch only)
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: bluefireteam/flutter-gh-pages@v9
      with:
        baseHref: '/'
        targetBranch: 'gh-pages'